services:
  flask:
    build:
      context: .
      dockerfile: flask_app/Dockerfile

    ports:
      - '80:80'

    environment:
      - TEAMKEY=XXXXXX1
      - CHALLENGEKEY=#oLq3j&ZcF
      - CHALLENGEKEY2=M9LQXpX^Us