version: '3'

volumes:
  my-django-data:

services:
  web:
    build:
      context: .
      dockerfile: django/Dockerfile

    volumes:
      - my-django-data:/media

    working_dir: '/code'

    ports:
      - '80:8000'

    environment:
      - TEAMKEY=XXXXXXX
      - CHALLENGEKEY=R^@LgvG5QD
