version: '3'

volumes:
  my-django-data:

services:
  flask:
    build:
      dockerfile: flask_app/Dockerfile

    ports:
      - '80:80'

    environment:
      - TEAMKEY=XXXXXXX
      - TEAM_ID=XXXXXXX
      - CHALLENGEKEY=#74q$j&zcB
      - CHALLENGEKEY2=R2LQXpy^Us
