version: '3'

volumes:
  my-django-data:

services:
  flask:
    build:
      context: .
      dockerfile: flask_app/Dockerfile

    ports:
      - '8003:5000'

    environment:
      - TEAMKEY=XXXXXXX
      - CHALLENGEKEY=#74q$j&zcB
      - TEAM_ID=XXXXXXX
