services:
  alpine:
    network_mode: bridge
    build:
      context: ./Alpine
      dockerfile: Dockerfile
    environment:
      - KEY_FlagFrenzy=/uploads/assembly-script.asm
    container_name: alpine_server
    volumes:
      - ./dev/:/uploads/
    ports:
      - "3000:3000"
    command: /bin/sh /app/entrypoint.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"