networks:
  encrpytion-forensics:

services:
  ubuntu-ssh:
    build:
      context: .
      dockerfile: Dockerfile
   
    ports:
      - "80:22"

    networks:
      - encrpytion-forensics

    environment:
      - TEAMKEY=XXXXXXX
      - PASSWORD=1234