name: MegaLinter with Auto-fix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MegaLinter
      run: npm install -g mega-linter-runner

    - name: Run MegaLinter with auto-fix
      run: npx mega-linter-runner --fix
      env:
        VALIDATE_PYTHON_PYLINT: true
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_HTML: true
        VALIDATE_MARKDOWN: true
        VALIDATE_YAML: true
        VALIDATE_BASH: true

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto-fix lint errors"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}