name: Docker Compose Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Find all docker-compose.yml files
      run: |
        for dir in $(find . -name 'docker-compose.yml' -exec dirname {} \;); do
          echo "Running docker-compose in $dir"
          cd $dir
          docker-compose up --build -d
          docker-compose ps
          docker-compose down
          cd -
        done