
name: Docker Compose Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Find all docker-compose.yml files and run tests
      run: |
        for dir in $(find . -name 'docker-compose.yml' -exec dirname {} \;); do
          echo "Running docker-compose in $dir"
          cd $dir
          docker-compose up --build -d
          docker-compose ps
          docker-compose down
          cd -
        done

  # docker-push:
  #   runs-on: ubuntu-latest
  #   needs: docker-test

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2

  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2

  #   - name: Install Docker Compose
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install -y docker-compose

  #   - name: Log in to Private Docker Registry
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.REGISTRY_USERNAME }}
  #       password: ${{ secrets.REGISTRY_PASSWORD }}
  #       registry: ${{ secrets.REGISTRY_URL }}

  #   - name: Find all docker-compose.yml files and build, push images
  #     run: |
  #       for dir in $(find . -name 'docker-compose.yml' -exec dirname {} \;); do
  #         echo "Running docker-compose in $dir"
  #         cd $dir
  #         docker-compose build
  #         for image in $(docker-compose config | grep 'image:' | awk '{print $2}'); do
  #           docker tag $image ${{ secrets.REGISTRY_URL }}/$(basename $image):latest
  #           docker push ${{ secrets.REGISTRY_URL }}/$(basename $image):latest
  #         done
  #         cd -
  #       done