name: Format and Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 autopep8 autoflake

    - name: Run autoflake and fix issues
      run: |
        autoflake --remove-all-unused-imports --remove-unused-variables --in-place --recursive .

    - name: Run black and fix issues
      run: |
        black .

    - name: Run isort and fix issues
      run: |
        isort .

    - name: Run autopep8 and fix issues
      run: |
        autopep8 --in-place --aggressive --aggressive -r .

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto-format code with autoflake, black, isort, and autopep8" || echo "No changes to commit"
        git push

    - name: Run flake8 (optional)
      continue-on-error: true
      run: |
        flake8 .