name: Super Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Super Linter
      uses: github/super-linter@v5
      env:
        VALIDATE_PYTHON_PYLINT: true
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_HTML: true
        VALIDATE_MARKDOWN: true
        VALIDATE_YAML: true
        VALIDATE_BASH: true
        DEFAULT_BRANCH: main