name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Daily at midnight

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Ensure Prettier is executable
        run: chmod +x ./node_modules/.bin/prettier

      - name: Run Prettier Check
        run: npx prettier --check .

      - name: Run Prettier Write
        run: npx prettier --write .

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: format code with Prettier' || echo "No changes to commit"
        if: success()

      - name: Push changes
        run: git push
        if: success()

      - name: Check for uncommitted changes
        run: git diff --exit-code
        shell: bash

  require-approval:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'

    steps:
      - name: Require approval
        uses: actions/github-script@v4
        with:
          script: |
            const { context, github } = require('@actions/github');
            const issues = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });
            const now = new Date();
            issues.data.forEach(async (issue) => {
              const lastUpdated = new Date(issue.updated_at);
              const daysSinceLastUpdate = (now - lastUpdated) / (1000 * 60 * 60 * 24);
              if (daysSinceLastUpdate > 7) {
                await github.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: 'This issue has been open for more than 7 days without interaction. Please take a look.',
                });
              }
            });